services:
  redis:
    image: redis:latest
    container_name: redis-bucket4j
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - rate_limiting_app-network
    restart: unless-stopped

  spring-boot-app:
    container_name: spring-rate-limiter
    image: spring/rate_limiting
    ports:
      - "8080:8080"
    networks:
      - rate_limiting_app-network
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local

networks:
  rate_limiting_app-network:
    driver: bridge
